"""B3 -- A_res against canonical GRUT access.  Independent re-implementation (numpy); canonical files are read-only evidence.
Classical sections use the earned Level-0 class (K = pin*I + weighted Laplacian, x' = -Kx, linear readouts).
Quantum sections are an AUXILIARY SUPPLIED ALGEBRAIC CLASS (EA-0: not defined on the earned substrate without a lift)."""
import itertools
import numpy as np
from scipy.linalg import expm, null_space
rng = np.random.default_rng(20261003)
def hdr(s): print("\n" + "=" * 78 + "\n" + s + "\n" + "=" * 78)

# ---------------- classical helpers ----------------
def lap(w): return np.diag(w.sum(1)) - w
def path_w(N, wts=None):
    w = np.zeros((N, N)); wts = np.ones(N - 1) if wts is None else wts
    for i in range(N - 1): w[i, i + 1] = w[i + 1, i] = wts[i]
    return w
def grid_w(L, rand=False):
    n = L * L; w = np.zeros((n, n))
    for x in range(L):
        for y in range(L):
            i = x * L + y
            for j in ([i + L] if x + 1 < L else []) + ([i + 1] if y + 1 < L else []):
                w[i, j] = w[j, i] = rng.uniform(0.8, 1.2) if rand else 1.0
    return w
def obs_matrix(K, C):
    C = np.atleast_2d(C); rows = [C]
    for _ in range(len(K) - 1): rows.append(rows[-1] @ K)
    return np.vstack(rows)
def obs_rank(K, C, tol=1e-9):
    """rank of the observable subspace, computed spectrally (robust): sum over eigenspaces of rank(C V_lambda)"""
    lam, V = np.linalg.eigh(K); r = 0; i = 0
    while i < len(lam):
        j = i
        while j + 1 < len(lam) and abs(lam[j + 1] - lam[i]) < 1e-8: j += 1
        Vb = V[:, i:j + 1]; s = np.linalg.svd(np.atleast_2d(C) @ Vb, compute_uv=False)
        r += int(np.sum(s > tol * max(1.0, np.abs(C).max()))); i = j + 1
    return r
def obs_subspace_spectral(K, c):
    lam, V = np.linalg.eigh(K); cols = []; i = 0
    while i < len(lam):
        j = i
        while j + 1 < len(lam) and abs(lam[j + 1] - lam[i]) < 1e-8: j += 1
        Vb = V[:, i:j + 1]; p = Vb @ (Vb.T @ c)
        if np.linalg.norm(p) > 1e-9: cols.append(p / np.linalg.norm(p))
        i = j + 1
    return np.linalg.qr(np.array(cols).T)[0]
def obs_subspace_krylov(K, c):
    Q = []; v = c / np.linalg.norm(c)
    for _ in range(len(K)):
        for q in Q: v = v - q * (q @ v)
        for q in Q: v = v - q * (q @ v)
        if np.linalg.norm(v) < 1e-8: break
        v = v / np.linalg.norm(v); Q.append(v); v = K @ v
    return np.array(Q).T
def span_gap(A, B):
    if A.shape[1] != B.shape[1]: return np.inf
    return max(np.linalg.norm(A - B @ (B.T @ A)), np.linalg.norm(B - A @ (A.T @ B)))
def transfer(K, C, omegas):
    C = np.atleast_2d(C); N = len(K)
    return np.array([C @ np.linalg.solve(1j * w * np.eye(N) + K, C.T) for w in omegas])
OM = np.linspace(0.0, 6.0, 121)

# ---------------- quantum (auxiliary class) helpers ----------------
PX = np.array([[0, 1], [1, 0]], complex); PY = np.array([[0, -1j], [1j, 0]]); PZ = np.diag([1.0 + 0j, -1]); I2 = np.eye(2)
def pauli(n, i, P):
    out = np.array([[1.0 + 0j]])
    for k in range(n): out = np.kron(out, P if k == i else I2)
    return out
def closure(gens, H=None, adh=False, max_sweeps=30, order=None):
    """unital *-algebra generated by gens; ad_H-closed if adh. Normalized candidates, relative tolerance (P-6 defect lesson)."""
    d = gens[0].shape[0]; B = []
    def add(M):
        v = M.reshape(-1); n = np.linalg.norm(v)
        if n < 1e-12: return False
        v = v / n
        for b in B: v = v - b * np.vdot(b, v)
        for b in B: v = v - b * np.vdot(b, v)
        if np.linalg.norm(v) > 1e-9: B.append(v / np.linalg.norm(v)); return True
        return False
    add(np.eye(d, dtype=complex)); gl = list(gens)
    if order is not None: gl = [gl[k] for k in order]
    for g in gl: add(g); add(g.conj().T)
    for _ in range(max_sweeps):
        grew = False; mats = [b.reshape(d, d) for b in B]
        if adh:
            for X in mats: grew |= add(H @ X - X @ H)
            mats = [b.reshape(d, d) for b in B]
        for X in mats:
            for Y in mats: grew |= add(X @ Y)
        if not grew: break
    return np.array(B).T                                                    # columns = orthonormal basis (vec)
def qgap(A, B):
    if A.shape[1] != B.shape[1]: return np.inf
    return max(np.linalg.norm(A - B @ (B.conj().T @ A)), np.linalg.norm(B - A @ (A.conj().T @ B)))
def center_dim(Bas):
    d = int(round(np.sqrt(Bas.shape[0]))); mats = [Bas[:, k].reshape(d, d) for k in range(Bas.shape[1])]
    # Z = sum c_k M_k commuting with every M_j
    rows = [np.array([(Mk @ Mj - Mj @ Mk).reshape(-1) for Mk in mats]).T for Mj in mats]
    return null_space(np.vstack(rows)).shape[1]
def herm_rand(d):
    A = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d)); return (A + A.conj().T) / 2
def probe_coherence(H, B, psi0, lam=0.5, ts=np.linspace(0, 10, 101)):
    """couple a fresh probe qubit through B (H_tot = H x 1 + lam B x sz_p), probe starts in |+>; return probe coherence <sx_p(t)>"""
    d = H.shape[0]; Ht = np.kron(H, I2) + lam * np.kron(B, PZ)
    plus = np.array([1, 1], complex) / np.sqrt(2); Psi = np.kron(psi0, plus)
    lam_, V = np.linalg.eigh(Ht); c = V.conj().T @ Psi; Ox = np.kron(np.eye(d), PX)
    out = []
    for t in ts:
        ps = V @ (np.exp(-1j * lam_ * t) * c); out.append(np.real(np.vdot(ps, Ox @ ps)))
    return np.array(out)

# =============================================================================================
hdr("B3-1 CLOSURE GIVEN SEED: is (D, A_seed) -> A_closure unique?")
print("  [classical, earned class] closure = observable (Krylov) subspace of (K, c); computed two independent ways")
N = 24; Kc = 0.3 * np.eye(N) + lap(path_w(N))
wg = np.triu(rng.uniform(0, 1, (N, N)), 1); wg = wg + wg.T; Kg = 0.3 * np.eye(N) + lap(wg)
cases = [("generic weighted net, generic seed", Kg, rng.normal(size=N)),
         ("C1-a path, end-site seed e1 (earned readout)", Kc, np.eye(N)[0]),
         ("C1-a path, reflection-symmetric seed e1 + e24 (symmetry-reducible)", Kc, np.eye(N)[0] + np.eye(N)[-1]),
         ("decoupled (abelian) control: K diagonal, seed e1 + e2", np.diag(np.arange(1, N + 1) * 0.37), np.eye(N)[0] + np.eye(N)[1])]
for name, K, c in cases:
    S1 = obs_subspace_krylov(K, c); S2 = obs_subspace_spectral(K, c)
    O = np.linalg.qr(rng.normal(size=(N, N)))[0]; S3 = obs_subspace_krylov(O @ K @ O.T, O @ c)
    print(f"  {name}: dim {S1.shape[1]} (Krylov) / {S2.shape[1]} (spectral); span gap {span_gap(S1, S2):.1e};"
          f" frame covariance gap {span_gap(O @ S1, S3):.1e}")
print("  -> classical closure is a definite function of (K, seed): unique, method-independent, frame-covariant.")
print("     symmetric seed closes on the reflection-even block (dim N/2); decoupled control closes on the seed's modes only.")

print("\n  [auxiliary quantum class] three closure RULES appear in the canonical record:")
print("     R_P5 = alg{I, H, B} (P-5 instrument);  R_P6 = unital *-alg of seed, ad_H-closed (P-6 closure, adh=True);")
print("     R_static = unital *-alg of seed, no dynamics (P-6 L-D2 sufficiency, adh=False)")
n = 2; z1z2 = pauli(n, 0, PZ) @ pauli(n, 1, PZ)
Hgen = herm_rand(4)
Hpar = sum(rng.normal() * M for M in [pauli(n, 0, PZ), pauli(n, 1, PZ), z1z2, pauli(n, 0, PX) @ pauli(n, 1, PX),
                                       pauli(n, 0, PY) @ pauli(n, 1, PY), pauli(n, 0, PX) @ pauli(n, 1, PY)])
Hab = np.diag(rng.normal(size=4)).astype(complex)
H3 = sum(rng.normal() * pauli(3, 0, P) for P in (PX, PY, PZ)) + sum(rng.normal() * pauli(3, 1, P) @ pauli(3, 2, Q)
                                                                     for P in (PX, PZ) for Q in (PX, PZ)) + 0.7 * pauli(3, 2, PZ)
qcases = [("generic H, seed sx1", Hgen, pauli(n, 0, PX)),
          ("parity-symmetric H ([H, z1z2] = 0), seed sz1", Hpar, pauli(n, 0, PZ)),
          ("abelian: diagonal H, diagonal seed", Hab, np.diag(rng.normal(size=4)).astype(complex)),
          ("site 1 DECOUPLED from a 2-spin hidden sector, seed sx1", H3, pauli(3, 0, PX))]
for name, H, Bs in qcases:
    a = closure([H, Bs]); b = closure([Bs], H, adh=True); c_ = closure([Bs])
    a2 = closure([Bs, H]); b2 = closure([Bs], H, adh=True, max_sweeps=60)
    print(f"  {name}: dims R_P5 {a.shape[1]}, R_P6 {b.shape[1]}, R_static {c_.shape[1]};"
          f" rule-internal reproducibility gaps {qgap(a, a2):.1e} / {qgap(b, b2):.1e}; center dims {center_dim(a)} / {center_dim(b)}")
V = expm(-1j * 0.7 * herm_rand(4)); b = closure([pauli(n, 0, PX)], Hgen, adh=True); bV = closure([V @ pauli(n, 0, PX) @ V.conj().T], V @ Hgen @ V.conj().T, adh=True)
print(f"  representation control (R_P6): cl(VSV^+; VHV^+) vs V cl(S;H) V^+ gap "
      f"{qgap(np.array([(V @ b[:, k].reshape(4, 4) @ V.conj().T).reshape(-1) for k in range(b.shape[1])]).T, bV):.1e}")
print("  -> GIVEN a closure rule, the closure is unique (reproducible, covariant). ACROSS the rules the canonical record uses,")
print("     the closure of the same (H, seed) differs when H has structure outside the seed's reach (decoupled-hidden case):")
print("     the closure rule is itself a declared convention (R_P5 imports H into the access algebra).")

# =============================================================================================
hdr("B3-2 SAME D, SAME Sigma, different seeds: identical closure / central structure, different downstream physics?")
print("  [classical, earned class] same K (and same net), single-site seeds")
for label, K in [("C1-a path N=24 (unit springs)", Kc),
                 ("weighted path N=24 (L0-1b-type, asymmetric weights)", 0.3 * np.eye(N) + lap(path_w(N, rng.uniform(0.6, 1.4, N - 1))))]:
    full = [k for k in range(N) if obs_rank(K, np.eye(N)[k]) == N]
    G = {k: transfer(K, np.eye(N)[k], OM)[:, 0, 0] for k in full}
    pairs = list(itertools.combinations(full, 2)); dif = [np.abs(G[a] - G[b]).max() for a, b in pairs]
    gauge = sum(d < 1e-10 for d in dif)
    print(f"  {label}: cyclic (informationally complete) single sites {len(full)}/{N}; all have IDENTICAL closure (R^N, trivial center);")
    print(f"     pairs {len(pairs)}: transfer-function-identical pairs {gauge} (automorphism / gauge); physically DISTINCT pairs {len(pairs) - gauge};"
          f" e1 vs e24 max|dG| = {np.abs(G[0] - G[N - 1]).max():.2e}" if 0 in G and N - 1 in G else "")
print("\n  [auxiliary quantum class] 3-spin chain 1-2-3, parity P = z1z2z3 conserved, seeds sz1 vs sz3 (P-6 L-B, re-implemented, new H)")
for trial in range(3):
    h = rng.uniform(0.6, 1.4, 3); J = rng.uniform(0.4, 1.0, 2); Jy = rng.uniform(0.1, 0.4, 2)
    H = sum(h[i] * pauli(3, i, PZ) for i in range(3)) + sum(J[i] * pauli(3, i, PX) @ pauli(3, i + 1, PX) + Jy[i] * pauli(3, i, PY) @ pauli(3, i + 1, PY) for i in range(2))
    P = pauli(3, 0, PZ) @ pauli(3, 1, PZ) @ pauli(3, 2, PZ)
    bL = closure([pauli(3, 0, PZ)], H, adh=True); bR = closure([pauli(3, 2, PZ)], H, adh=True)
    aL = closure([H, pauli(3, 0, PZ)]); aR = closure([H, pauli(3, 2, PZ)])
    psi0 = np.kron(np.kron(np.array([np.cos(0.4), np.sin(0.4)]), np.array([1, 0])), np.array([np.cos(1.1), np.sin(1.1)])).astype(complex)
    cL = probe_coherence(H, 0.5 * pauli(3, 0, PZ), psi0); cR = probe_coherence(H, 0.5 * pauli(3, 2, PZ), psi0)
    print(f"   trial {trial}: [H,P] {np.linalg.norm(H @ P - P @ H):.0e}; R_P6 dims {bL.shape[1]}/{bR.shape[1]} gap {qgap(bL, bR):.1e}, center {center_dim(bL)}/{center_dim(bR)};"
          f" R_P5 dims {aL.shape[1]}/{aR.shape[1]} gap {qgap(aL, aR):.1e}; probe coherence max diff {np.abs(cL - cR).max():.3f}")
print("  Sigma check: the net (chain 1-2-3 / path) is IDENTICAL for both seeds and both are END sites of it, so Sigma's")
print("  graph role cannot separate them; any rule that does (e.g. 'the end with larger field') is an added criterion.")

# =============================================================================================
hdr("B3-3 informational completeness vs readout selection (classical Level-0)")
K = Kc; full = [k for k in range(N) if obs_rank(K, np.eye(N)[k]) == N]; nonfull = [k for k in range(N) if k not in full]
print(f"  C1-a N=24: single-site readouts that are informationally complete (full observability rank): {len(full)}; not: {nonfull} (sites, 0-based)")
lin = sum(obs_rank(K, rng.normal(size=N)) == N for _ in range(200))
print(f"  random linear functionals h(x) = c.x: informationally complete {lin}/200")
G1 = transfer(K, np.eye(N)[0], OM)[:, 0, 0]; G24 = transfer(K, np.eye(N)[-1], OM)[:, 0, 0]; G5 = transfer(K, np.eye(N)[5], OM)[:, 0, 0]
print(f"  end sites e1, e24 (symmetry orbit): max|dG| {np.abs(G1 - G24).max():.1e} -> GAUGE pair; e1 vs e6 max|dG| {np.abs(G1 - G5).max():.3f} -> different physics")
print("  -> READOUT COMPLETENESS != READOUT SELECTION: completeness holds for an open dense set of readouts, which differ physically.")

# =============================================================================================
hdr("B3-4 GS1 inverse: given the SAME K / Sigma / geometry, is the access boundary reconstructable?")
L = 3; wgr = grid_w(L, rand=True); Kq = 0.3 * np.eye(9) + lap(wgr)
decl = {"full site-resolved": list(range(9)), "boundary {0,2,8}": [0, 2, 8], "other 3-set {1,3,5}": [1, 3, 5], "single site {0}": [0], "single site {4}": [4]}
for name, S in decl.items():
    C = np.eye(9)[S]; Gs = transfer(Kq, C, [0.0, 0.5])
    rec = None
    if len(S) == 9: rec = np.abs(np.linalg.inv(Gs[0]) - Kq).max()
    print(f"  {name}: observability rank {obs_rank(Kq, C)}/9; static response trace {np.trace(Gs[0]).real:.3f}" + (f"; full-access K reconstruction error {rec:.1e}" if rec is not None else ""))
cnt3 = [S for S in itertools.combinations(range(9), 3) if obs_rank(Kq, np.eye(9)[list(S)]) == 9]
cnt1 = [k for k in range(9) if obs_rank(Kq, np.eye(9)[[k]]) == 9]
print(f"  admissible informationally complete boundaries on the SAME K: singletons {len(cnt1)}/9, 3-sets {len(cnt3)}/84")
print("  candidate inverse selectors: max-information -> the full set (monotone: any superset dominates; never the declared boundary);")
print(f"  min-cardinality complete -> {len(cnt1)} tied singletons; GS1-selection power -> full access only. None returns a given declared boundary.")
print("  -> GS1 IS ONE-WAY: declared access -> geometry, not geometry -> access.")

# =============================================================================================
hdr("B3-6 state-dependent VALUES on a fixed access structure (classical Gaussian, site 1 vs rest)")
def mi_gauss(S, a):
    b = [i for i in range(len(S)) if i not in a]
    return 0.5 * np.log(np.linalg.det(S[np.ix_(a, a)]) * np.linalg.det(S[np.ix_(b, b)]) / np.linalg.det(S))
Ob = obs_subspace_krylov(Kc, np.eye(N)[0])
for t, S0 in [("uncorrelated prep", np.eye(N)), ("correlated prep", np.eye(N) + 0.6 * (np.eye(N, k=1) + np.eye(N, k=-1)))]:
    M = expm(-Kc * 1.0); St = M @ S0 @ M.T + 2 * 0.3 * np.eye(N) * 0.5
    print(f"  {t}: MI(site1 : rest) at t=1 = {mi_gauss(St, [0]):.4f}; access structure (closure dim) unchanged = {Ob.shape[1]}")
print("  -> values vary with the state; available effects / closure / fragments / seed do not: NOT endogenous access (EA-0 (a), not (c)).")

# =============================================================================================
hdr("B3-7 resolution / hierarchy order: is a final finite truncation fixed by D?")
seed = np.eye(N)[0]
def moments(K, n): return np.array([seed @ np.linalg.matrix_power(K, k) @ seed for k in range(n)])
base = np.ones(N - 1)
for r in (3, 6, 10):
    w2 = base.copy(); w2[r] = 1.3
    m0, m1 = moments(Kc, 2 * N), moments(0.3 * np.eye(N) + lap(path_w(N, w2)), 2 * N)
    first = int(np.argmax(np.abs(m0 - m1) > 1e-9 * np.abs(m0).max()))
    dG = np.abs(transfer(Kc, seed, OM)[:, 0, 0] - transfer(0.3 * np.eye(N) + lap(path_w(N, w2)), seed, OM)[:, 0, 0]).max()
    print(f"  hidden edge ({r},{r+1}) changed: end-site Markov moments agree through order {first - 1}, first differ at order {first};"
          f" max transfer difference {dG:.2e}")
for delta in (1e-2, 1e-4, 1e-6, 1e-8):
    det = []
    for r in range(N - 1):
        w2 = base.copy(); w2[r] = 1.3
        dG = np.abs(transfer(Kc, seed, OM)[:, 0, 0] - transfer(0.3 * np.eye(N) + lap(path_w(N, w2)), seed, OM)[:, 0, 0]).max()
        det.append(dG > delta)
    print(f"  resolution threshold delta = {delta:.0e}: perturbed edges detectable at the end site {sum(det)}/{N - 1} (deepest detectable edge {max([r for r in range(N - 1) if det[r]], default=None)})")
print("  -> sufficiency is order- and threshold-relative; the required order / delta is set by the unknown alternative, not by D.")

# =============================================================================================
hdr("B3-8 path-dependent minimality (classical re-implementation of the P-6 L-D2 logic)")
Lu = 5; Ku = 0.3 * np.eye(25) + lap(grid_w(Lu))
deg = np.sum(np.abs(np.diff(np.linalg.eigvalsh(Ku))) < 1e-8)
print(f"  uniform 5x5 grid: degenerate eigenvalue pairs {deg} -> no single readout is complete (needs >= 2 outputs)")
def suff(S): return obs_rank(Ku, np.eye(25)[sorted(S)]) == 25 if S else False
def elim(pool, order):
    S = list(pool)
    for g in order:
        if suff([x for x in S if x != g]): S = [x for x in S if x != g]
    return sorted(S)
found = None
for pool in itertools.combinations(range(25), 5):
    if not suff(pool): continue
    Mf = elim(pool, list(pool)); Mr = elim(pool, list(pool)[::-1])
    if Mf != Mr: found = (pool, Mf, Mr); break
pool, Mf, Mr = found
minimal = lambda M: suff(M) and all(not suff([x for x in M if x != g]) for g in M)
print(f"  pool (first lexicographic 5-site pool with differing outcomes) {pool}: forward elimination -> {Mf}, reverse -> {Mr};"
      f" both sufficient AND minimal: {minimal(Mf)} / {minimal(Mr)}")
allmin = [S for k in (1, 2, 3, 4, 5) for S in itertools.combinations(pool, k) if minimal(list(S))]
print(f"  all minimal sufficient subsets of this pool: {allmin}")
print("  -> MINIMALITY DOES NOT SELECT A_seed (path-dependent; several minimal sets).")

# =============================================================================================
hdr("B3-9 / B3-10 fragment grouping and temporal access (same net, same D; 'how many fragments record site 12?')")
print("  record criterion: posterior variance of x_12(0) (prior 1) from noisy samples (sigma 1e-3) of the fragment, below threshold")
target = 12
def post_var(K, F, T, dt, sig=1e-3):
    C = np.eye(N)[F]; J = np.zeros((N, N))
    for t in np.arange(dt, T + 1e-12, dt):
        M = C @ expm(-K * t); J += M.T @ M / sig ** 2
    return np.linalg.inv(J + np.eye(N))[target, target]          # prior variance 1
groupings = {"single sites (24)": [[k] for k in range(N)], "adjacent pairs (12)": [[2 * k, 2 * k + 1] for k in range(12)],
             "blocks of 6 (4)": [list(range(6 * k, 6 * k + 6)) for k in range(4)]}
for (T, dt) in [(1.0, 0.5), (5.0, 0.5), (20.0, 2.0)]:
    for delta in (0.6, 0.3):
        row = []
        for g, frags in groupings.items():
            v = [post_var(Kc, F, T, dt) for F in frags]
            row.append(f"{g}: {sum(x < delta for x in v)}/{len(frags)}")
        print(f"  horizon T={T:>4}, cadence dt={dt}, threshold var<{delta}: " + "; ".join(row))
print(f"  D's own timescales: slowest relaxation rate {np.linalg.eigvalsh(Kc)[0]:.2f}, fastest {np.linalg.eigvalsh(Kc)[-1]:.2f} -- units, not a schedule")
print("  -> the 'record redundancy' count changes with grouping, horizon, cadence and threshold; nothing in K or the net selects them.")
