"""SCOUT-1 W4-OG: operator generation / closure hostile against TC-4.

Conserved scalar on a ring, bond noise, Lax-Friedrichs flux (monotone):
  du/dt = -d_x F,  F = -(u_{i+1}-u_i) + J_LF(u_i, u_{i+1}) + sqrt(2 T(ubar)/dt) eta
Microscopic current J(u) = lam3 u^3 ONLY (lambda_2,bare = 0 in every run).

W4-2 background shift: mean density u0 (conserved sector) in {0, 0.1, 0.3, 0.6}; T(u) = T constant (Z2 symmetric
     microscopically). Expansion: lambda_2,eff = 3 lam3 u0.
W4-3 generation: u0 = 0 but Z2 broken only through the NOISE: T(u) = T (1 + a u).
     Coarse-grained current J_eff(ubar) = <J(ubar + d)> = lam3 (ubar^3 + 3 ubar sigma^2(ubar) + kappa3(ubar)),
     sigma^2(ubar) ~ T (1 + a ubar)  =>  lambda_2,eff = 3 lam3 T a  generated by coarse-graining (no bare u^2 term).
     Controls: a = 0 (Z2 symmetric: no generation); lam3 = 0 with a != 0 (no nonlinear current to generate from).
Static check: measured local variance vs u0 for T(u) = T(1 + a u).
"""
import sys
import numpy as np

rng = np.random.default_rng(int(sys.argv[2]) if len(sys.argv) > 2 else 7)


def simulate(lam3, u0, a, T=1.0, N=4096, dt=0.02, tmax=2000, reps=4, var_only=False):
    times = np.unique(np.round(np.logspace(0, np.log10(tmax), 24) / dt).astype(int))
    W2 = np.zeros(len(times))
    var_acc = []
    J = lambda v: lam3 * v ** 3
    Jp = lambda v: 3 * lam3 * v ** 2
    for _ in range(reps):
        u = np.full(N, float(u0))
        k = 0
        for s in range(1, times[-1] + 1):
            up = np.roll(u, -1)
            amax = np.maximum(Jp(u), Jp(up))
            FJ = 0.5 * (J(u) + J(up)) - 0.5 * amax * (up - u)
            Tl = T * np.clip(1 + a * 0.5 * (u + up), 0.05, None)
            F = -(up - u) + FJ + np.sqrt(2 * Tl / dt) * rng.standard_normal(N)
            u = u - dt * (F - np.roll(F, 1))
            if s == times[k]:
                W2[k] += np.var(np.cumsum(u - u0))
                k += 1
            if var_only and s * dt > 50 and s % 50 == 0:
                var_acc.append(np.var(u))
        if var_only:
            break
    t = times * dt
    return t, np.sqrt(W2 / reps), (np.mean(var_acc) if var_acc else None)


def exps(t, W):
    out = []
    for a_, b_ in ((5, 50), (50, 500), (500, 2000)):
        m = (t >= a_) & (t <= b_)
        out.append(np.polyfit(np.log(t[m]), np.log(W[m]), 1)[0])
    return out


if __name__ == "__main__":
    which = sys.argv[1]
    if which == "shift":
        print("=== W4-2 background shift: J = 0.5 u^3, T(u) = 1, sector u0 (lambda_2,eff = 1.5 u0) ===")
        for u0 in (0.0, 0.1, 0.3, 0.6):
            t, W, _ = simulate(0.5, u0, 0.0)
            print(f"  u0 = {u0:3.1f} (lam2_eff = {1.5 * u0:.2f}): growth exponents [5-50, 50-500, 500-2000] = "
                  + ", ".join(f"{x:.3f}" for x in exps(t, W)), flush=True)
    elif which == "gen":
        print("=== W4-3 generation at u0 = 0: lambda_2,bare = 0; Z2 broken only via noise T(u) = 1 + a u ===")
        for lam3, a, lab in ((0.5, 0.0, "Z2 control (a = 0)"), (0.5, 0.8, "a = 0.8 (prediction lam2_eff = 3*0.5*0.8 = 1.2)"),
                             (0.0, 0.8, "no nonlinear current (lam3 = 0, a = 0.8)")):
            t, W, _ = simulate(lam3, 0.0, a)
            print(f"  lam3 = {lam3}, {lab:48s}: growth exponents = " + ", ".join(f"{x:.3f}" for x in exps(t, W)), flush=True)
    elif which == "var":
        print("=== static check: local variance sigma^2(u0) vs T(1 + a u0), a = 0.8, lam3 = 0.5 ===")
        for u0 in (-0.3, 0.0, 0.3):
            _, _, v = simulate(0.5, u0, 0.8, tmax=300, var_only=True)
            print(f"  u0 = {u0:+.1f}: measured sigma^2 = {v:.3f}   T(1 + a u0) = {1 + 0.8 * u0:.3f}", flush=True)
