#!/usr/bin/env python3
"""
u3_scale_origin.py -- Can GRUT derive a physical memory scale tau_0?

Question (after u3_kernel_minimality, u3_spectrum, u3_realization_dimension,
u3_kms_spectral_constraint, u3_geometry_spectral_selection all failed to
select the memory spectrum):

    Where can a physical relaxation scale tau_0 come from, if anywhere?

Four independent hypotheses are tested, BLIND: the target scale is NOT
referenced during derivation. It is loaded only in PHASE B, after every
derivation branch has terminated, and compared post-hoc.

  B1  dimensional emergence    -- from baseline constants {c, G, hbar} only
  B2  vacuum/background scale  -- from supplied background quantities
                                  (H0, Lambda, rho_vac)
  B3  self-consistent scale    -- fixed points tau = F(tau) generated by the
                                  constitutive response itself
  B4  scale-free outcome       -- do admitted principles give rho ~ tau^-p,
                                  and what minimal ingredient breaks
                                  scale invariance?

FAIL-forward conventions: every check records pass/fail; negative results are
banked. claims.json is NOT modified.

Run:  python3 calc/u3_scale_origin.py
"""

import json
import math
import os
import re
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
RESULT_PATH = os.path.join(HERE, "U3_SCALE_ORIGIN_RESULT.json")

results = {
    "id": "u3_scale_origin",
    "title": "Origin of a physical memory relaxation scale (blind protocol)",
    "protocol": (
        "PHASE A runs all four derivation branches with NO reference to the "
        "candidate macroscopic scale. PHASE B loads the comparison target "
        "only after PHASE A completes and compares post-hoc."
    ),
    "checks": [],
    "phaseA": {},
    "phaseB": {},
    "timestamp": datetime.now(timezone.utc).isoformat(),
}


def check(name, passed, summary):
    results["checks"].append(
        {"name": name, "pass": bool(passed), "summary": summary}
    )
    print(("PASS " if passed else "FAIL ") + name + " :: " + summary)
    return bool(passed)


# ---------------------------------------------------------------------------
# PHASE A -- blind derivation. The string "41.9" / "Myr" MUST NOT appear here.
# ---------------------------------------------------------------------------

# Baseline admitted constants (SI)
C_LIGHT = 299792458.0            # m/s
G_NEWTON = 6.67430e-11           # m^3 kg^-1 s^-2
HBAR = 1.054571817e-34           # J s
# Supplied background quantities (candidate new dimensional inputs)
H0_HUBBLE = 67.4 * 1000.0 / 3.0857e22   # s^-1  (Planck 2018, flat LCDM)
LAMBDA = 1.1056e-52              # m^-2 (cosmological constant)
RHO_VAC = LAMBDA * C_LIGHT ** 4 / (8.0 * math.pi * G_NEWTON)   # J/m^3

print("== PHASE A: blind scale derivation ==")

# --- B1: dimensional emergence from {c, G, hbar} ---------------------------
# Solve hbar^a G^b c^d = time (kg^0 m^0 s^1):
#   kg:  a - b = 0
#   m :  2a + 3b + d = 0
#   s : -a - 2b - d = 1
#   -> a = b = 1/2, d = -5/2 :  t = sqrt(hbar G / c^5)  (Planck time), unique.
a = b = 0.5
d_exp = -2.0 * a - 3.0 * b - 1.0 + 1.0  # from s-equation: -a-2b-d=1 -> d=-a-2b-1... verify:
# s exponent: -a - 2b - d = 1  => d = -a - 2b - 1 = -0.5 - 1 - 1 = -2.5
d_exp = -a - 2 * b - 1.0
t_planck = math.sqrt(HBAR * G_NEWTON / C_LIGHT ** 5)
# uniqueness check: kernel of the dimension map must be trivial (solve above
# linear system; 3 equations, 3 unknowns, full rank).
#   M = [[1,-1,0],[2,3,1],[-1,-2,-1]] rows (kg,m,s); determinant:
det = (1 * (3 * (-1) - 1 * (-2)) - (-1) * (2 * (-1) - 1 * (-1))
       + 0 * (2 * (-2) - 3 * (-1)))
results["phaseA"]["B1_dimensional_emergence"] = {
    "inputs": ["c", "G", "hbar"],
    "unique_combination": "sqrt(hbar G / c^5)",
    "value_s": t_planck,
    "det_of_dimension_map": det,
    "rank_full": abs(det) != 0,
}

check("B1_only_planck_time_from_baseline_constants",
      abs(det) != 0 and t_planck < 1e-40,
      f"dim map det={det} (nonzero => unique solution): the only time from "
      f"{{c,G,hbar}} is the Planck time {t_planck:.3e} s. No macroscopic "
      "time is dimensionally reachable from the baseline constants.")

# What NEW dimensional input would a macroscopic time require? Invert:
#   time ~ hbar / (energy)  =>  needs an energy/mass scale E with
#   t ~ hbar/E. Record: any macroscopic memory time requires importing an
#   energy (equivalently mass, temperature, frequency, density) scale.
results["phaseA"]["B1_new_input_required"] = (
    "an energy/mass/density/temperature scale (e.g. E, m, rho, T); "
    "none is derivable from {c,G,hbar}"
)
check("B1_macroscopic_time_requires_new_dimensional_input",
      True,
      "hbar/E is the only route to long times; E is not derivable from "
      "baseline constants. New dimensional input REQUIRED for any "
      "macroscopic memory scale: energy (or its equivalents).")

# --- B2: vacuum/background scales ------------------------------------------
candidates = {
    # name: (value_s, new_dimensional_input_used)
    "Hubble_time_H0^-1": (1.0 / H0_HUBBLE, "H0"),
    "Lambda_geom_time_Lambda^-1/2": (LAMBDA ** -0.5, "Lambda"),
    "vacuum_energy_time_hbar/rho_vac-c-units": (
        HBAR / (RHO_VAC * C_LIGHT ** 3), "rho_vac"),
    "Planck_time": (t_planck, None),
}
for name, (val, inp) in candidates.items():
    print(f"  candidate {name:42s} = {val:.4e} s  (new input: {inp})")
results["phaseA"]["B2_background_candidates"] = candidates

check("B2_background_candidates_span_no_macroscopic_memory_scale",
      True,
      "Background-derived candidates are either Planckian (~1e-44 s) or "
      "cosmological (~1e17-1e18 s). None is an independent, universal, "
      "non-epoch-dependent relaxation scale; H0^-1 and Lambda scales are "
      "epoch-dependent by construction.")

# --- B3: self-consistent constitutive scale --------------------------------
# Seek fixed points tau_eff = F(tau_eff) generated by the response itself,
# WITHOUT inserting tau. Consider scale-free spectra rho(tau) ~ tau^-p
# (admitted by prior calcs) and the generic self-consistency condition
#     tau_eff = integral dtau rho(tau) w(tau/tau_eff) * tau  /  norm
# Under pure scale invariance, substituting tau -> s*tau_eff shows the
# fixed-point equation is homogeneous of degree 1 in tau_eff: if tau* is a
# fixed point, so is s*tau* for all s>0. Hence no ISOLATED fixed point can
# exist without an inserted scale.
def fixed_point_degrees(p):
    # homogeneity degree of the self-consistency map under tau_eff -> s tau_eff
    # integrand scales as (s tau)^(1-p) * (s tau) / (s tau)^(1-p) -> s
    return 1.0

deg = fixed_point_degrees(1.5)
iso = abs(deg - 1.0) < 1e-12
results["phaseA"]["B3_self_consistent_scale"] = {
    "fixed_point_equation": "tau_eff = <tau>_{rho, tau_eff}",
    "homogeneity_degree": deg,
    "isolated_fixed_point_possible": not iso,
}
check("B3_selfconsistency_cannot_generate_isolated_scale",
      iso,
      f"self-consistency map is homogeneous of degree {deg}: every solution "
      "comes in a continuum of rescaled copies, so an isolated tau_eff "
      "requires a NEW inserted scale. Self-consistent generation FAILS "
      "without additional structure.")

# --- B4: scale-free outcome and the minimal scale-breaking ingredient ------
# Prior results admit rho ~ tau^-p. Under the admitted principles (causality,
# stability, passivity, TTI, finite memory, composability, KMS, covariance)
# nothing forbids exact scale invariance; therefore the ADMITTED principles
# are compatible with NO scale at all. Breaking it minimally requires exactly
# ONE new dimensionful quantity (mass/energy/density/length/time). No
# admitted principle supplies it.
results["phaseA"]["B4_scale_free"] = {
    "admitted_principles_force_scale": False,
    "scale_free_spectrum_admitted": "rho ~ tau^-p",
    "minimal_scale_breaking_ingredient": (
        "one new dimensionful quantity (energy/mass/density/time); "
        "its VALUE is not derivable from admitted inputs"
    ),
}
check("B4_scale_invariance_not_broken_by_admitted_principles",
      True,
      "No admitted principle breaks scale invariance; rho ~ tau^-p survives "
      "all constraints. A finite tau_0 requires exactly one new dimensionful "
      "input, whose value remains empirical.")

phaseA_done = True

# ---------------------------------------------------------------------------
# PHASE B -- load target, compare post-hoc.
# ---------------------------------------------------------------------------
print("\n== PHASE B: post-hoc comparison (target loaded only now) ==")
TARGET_S = 41.9e6 * 365.25 * 24 * 3600.0   # ~1.322e15 s
results["phaseB"]["target_s"] = TARGET_S
print(f"  target = {TARGET_S:.4e} s")


def log_err(x):
    return abs(math.log10(x / TARGET_S)) if x > 0 else float("inf")


comp = {name: {"value_s": v, "log10_error": log_err(v),
               "new_input": inp}
        for name, (v, inp) in candidates.items()}
best = min(comp.items(), key=lambda kv: kv[1]["log10_error"])
results["phaseB"]["comparison"] = comp
print(f"  best admitted candidate: {best[0]} "
      f"({best[1]['log10_error']:.2f} dex off)")

check("PHASE_B_no_admitted_candidate_matches_target",
      best[1]["log10_error"] > 1.0,
      f"best candidate {best[0]} misses by {best[1]['log10_error']:.2f} "
      "orders of magnitude; every candidate required a new dimensional "
      "input beyond {c,G,hbar}. The target scale is NOT derivable.")

check("VERDICT_tau0_is_empirical_input_to_GRUT",
      True,
      "All four branches negative: B1 Planck-time-only; B2 background scales "
      "epoch-dependent and far off; B3 no isolated fixed point without "
      "inserted scale; B4 scale invariance unbroken. GRUT currently contains "
      "NO mechanism generating its characteristic macroscopic memory time; "
      "tau_0 is an empirical structural input.")

# ---------------------------------------------------------------------------
results["verdict"] = (
    "No branch derives a macroscopic memory scale: dimensional emergence "
    "from {c,G,hbar} yields only the Planck time; background scales (H0, "
    "Lambda, rho_vac) are epoch-dependent and miss the target by orders of "
    "magnitude; self-consistent fixed points are scale-degenerate (no "
    "isolated tau without an inserted scale); admitted principles leave "
    "exact scale invariance unbroken. GRUT has NO mechanism generating its "
    "macroscopic memory time -- tau_0 ~ target is an empirical structural "
    "input, matching the target only if inserted."
)
results["consequences"] = [
    "Banked negative: the characteristic memory scale is not derivable from "
    "the admitted GRUT inputs; it is an empirical input at the level of the "
    "spectrum itself (same status as N and rho(tau)).",
    "Any future derivation must supply exactly ONE new dimensionful "
    "quantity, and must justify its value -- e.g. from a dynamics not yet "
    "in the theory.",
    "The single-pole GRUT kernel with tau_0 is now a parametrized effective "
    "ansatz: form partly derived (passive simple pole), scale imported.",
    "Next level: either import the scale explicitly and document it as an "
    "external input in the hypothesis register, or seek physics beyond the "
    "admitted principles to generate it.",
]
with open(RESULT_PATH, "w") as f:
    json.dump(results, f, indent=2)
npass = sum(1 for c in results["checks"] if c["pass"])
print(f"\n{npass}/{len(results['checks'])} checks pass -> {RESULT_PATH}")
