#!/usr/bin/env python3
"""build_calc_manifest: the calculation set, as a committed fact rather than a directory listing.

WHY IT IS A FILE AND NOT A QUERY. Appendix E's calculation index and the emitted count `n_calcs`
must describe the REPOSITORY, not whatever happens to be sitting in `calc/` when the document is
built -- on 2026-08-18 a gitignored mutant, left behind by a mutation battery, had inserted itself
as a row in the calculation index of a document that gets committed.

The obvious fix -- ask git from inside the emitter -- breaks a STANDING INVARIANT: the emitter must
not shell out, because the drift check would then run pytest from inside pytest and adding a test
would change the number the block asserts. Routing the same subprocess through a helper module the
emitter imports would satisfy the letter of that guard while defeating it, which this program
treats as a defect in its own right.

So the set is written down HERE, committed, and read by the emitter with plain file I/O -- and
because a hand-maintained list that nothing derives is the exact defect Wave 7 found in the
one-number guard, test_public_doc.py DERIVES the truth from git and fails if this file disagrees.
Adding a calculation is therefore a two-line act: add the file, regenerate this manifest.

    python3 build_calc_manifest.py --write     regenerate from git
    python3 build_calc_manifest.py --check     compare against git (exit 1 on drift)
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "CALC_MANIFEST.txt")
HEADER = ("# The calculation set, generated by build_calc_manifest.py from `git ls-files`.\n"
          "# Read by emit_public_numbers.calc_files(); verified against git by test_public_doc.\n"
          "# Never hand-edit: add the calculation, then regenerate.\n")


def from_git():
    out = subprocess.run(["git", "ls-files", "calc/*.py"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.split()
    return sorted(os.path.basename(f) for f in out)


def from_manifest():
    with open(MANIFEST) as f:
        return sorted(line.strip() for line in f
                      if line.strip() and not line.startswith("#"))


def main():
    want = from_git()
    if "--write" in sys.argv:
        with open(MANIFEST, "w") as f:
            f.write(HEADER + "".join(n + "\n" for n in want))
        print(f"wrote {MANIFEST} ({len(want)} calculations)")
        return 0
    have = from_manifest()
    if have != want:
        print("DRIFT: CALC_MANIFEST.txt does not match the repository.")
        for n in sorted(set(want) - set(have)):
            print(f"  tracked but not in the manifest: {n}")
        for n in sorted(set(have) - set(want)):
            print(f"  in the manifest but not tracked: {n}")
        return 1
    print(f"calculation manifest matches the repository ({len(want)} calculations).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
