#!/usr/bin/env python3
"""emit_audit_matrix: the ONE place the reality-audit summary comes from.

Third sibling of emit_public_numbers.py (register counts) and emit_gate_status.py (gate counts).
This one covers AUDIT counts, and it exists because the tier x verdict matrix was hand-typed and
summed to 72 against a 71-node register -- in the same message asserting the numbers now emit from
the graph. Five prose-vs-artifact drifts in this stretch; every one was a number that had been true
earlier, retyped later. A summary that READS the artifact cannot drift.

Run:  python3 emit_audit_matrix.py <YYYY-MM-DD>            print the block
      python3 emit_audit_matrix.py <YYYY-MM-DD> --write    write ../AUDIT_MATRIX.md
      python3 emit_audit_matrix.py <YYYY-MM-DD> --check    regenerate and diff

Date is an ARGUMENT, never today() -- inherited from emit_public_numbers.py so the block is
diffable. Reads REALITY_AUDIT_RESULTS.json and claims.json. Interprets nothing.

IT FAILS LOUDLY on an arithmetic inconsistency rather than printing a pretty wrong table: if the
audit rows do not cover the register exactly once, that is reported as an ERROR line in the output.
"""
import json, os, re, sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "AUDIT_MATRIX.md")
GROUPS = ("shown", "assumed", "__other__")


def block(date):
    reg = {c["id"]: c.get("tier") for c in json.load(
        open(os.path.join(HERE, "claims.json")))["claims"]} if False else None
    with open(os.path.join(HERE, "claims.json")) as f:
        reg = {c["id"]: c.get("tier") for c in json.load(f)["claims"]}
    ap = os.path.join(ROOT, "REALITY_AUDIT_RESULTS.json")
    if not os.path.exists(ap):
        return "# AUDIT_MATRIX\n\n*(REALITY_AUDIT_RESULTS.json absent)*\n"
    raw = json.load(open(ap))
    rows = raw if isinstance(raw, list) else (raw.get("nodes") or raw.get("results") or [])
    rows = [r for r in rows if isinstance(r, dict) and r.get("id")]

    cell = defaultdict(Counter)
    verdicts, seen = set(), Counter()
    for r in rows:
        nid = r["id"]
        seen[nid] += 1
        tier = reg.get(nid, r.get("tier"))
        g = tier if tier in ("shown", "assumed") else "__other__"
        v = r.get("verdict", "(none)")
        verdicts.add(v)
        cell[g][v] += 1
    verdicts = sorted(verdicts)

    L = ["# AUDIT_MATRIX -- emitted, never hand-typed", "",
         "*Generated by `provenance/emit_audit_matrix.py %s` from "
         "`REALITY_AUDIT_RESULTS.json` + `provenance/claims.json`. "
         "Do not edit: regenerate.*" % date, ""]

    # --- integrity, printed BEFORE the table so a wrong table cannot read as right ---
    errs = []
    if len(rows) != len(reg):
        errs.append("row count %d != register node count %d" % (len(rows), len(reg)))
    dupes = [k for k, n in seen.items() if n > 1]
    if dupes:
        errs.append("duplicated ids: %s" % ", ".join(sorted(dupes)[:8]))
    missing = sorted(set(reg) - set(seen))
    if missing:
        errs.append("%d register nodes absent from the audit: %s"
                    % (len(missing), ", ".join(missing[:8])))
    extra = sorted(set(seen) - set(reg))
    if extra:
        errs.append("%d audited ids not in the register: %s" % (len(extra), ", ".join(extra[:8])))
    if errs:
        L += ["> **ERROR -- the matrix does not cover the register exactly once.**", ""]
        L += ["> - " + e for e in errs] + [""]
    else:
        L += ["*Integrity: %d audit rows cover %d register nodes exactly once.*"
              % (len(rows), len(reg)), ""]

    L += ["| tier | " + " | ".join(verdicts) + " | row total |",
          "|---" * (len(verdicts) + 2) + "|"]
    coltot, grand = Counter(), 0
    for g in GROUPS:
        label = g if g != "__other__" else "all others"
        n = sum(cell[g][v] for v in verdicts)
        grand += n
        for v in verdicts:
            coltot[v] += cell[g][v]
        L.append("| %s | %s | **%d** |" % (label, " | ".join(str(cell[g][v]) for v in verdicts), n))
    L.append("| **column total** | %s | **%d** |"
             % (" | ".join("**%d**" % coltot[v] for v in verdicts), grand))
    L += ["", "*Register tiers, for reference:* " + ", ".join(
        "%s %d" % (t, n) for t, n in sorted(Counter(reg.values()).items())) + ".", ""]

    off = [(g, v, cell[g][v]) for g in GROUPS for v in verdicts
           if cell[g][v] and not (g == "assumed" and v.startswith("NULL"))
           and not v.startswith("UNRESOLVED")]
    L += ["## Off-diagonal entries (the findings, per REALITY_AUDIT_BRIEF.md ADDED-2)", ""]
    L += ["- **%s** -> %s: %d" % (g if g != "__other__" else "all others", v, n)
          for g, v, n in off] or ["- *(none)*"]
    L.append("")
    return "\n".join(L) + "\n"


def main(a):
    if len(a) < 2 or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", a[1]):
        print("usage: emit_audit_matrix.py <YYYY-MM-DD> [--write|--check]", file=sys.stderr)
        return 2
    text, mode = block(a[1]), (a[2] if len(a) > 2 else "")
    if mode == "--write":
        open(OUT, "w").write(text); print("wrote %s" % OUT); return 0
    if mode == "--check":
        if not os.path.exists(OUT):
            print("MISSING: %s" % OUT, file=sys.stderr); return 1
        strip = lambda t: "\n".join(l for l in t.splitlines() if "emit_audit_matrix.py" not in l)
        if strip(open(OUT).read()) == strip(text):
            print("AUDIT_MATRIX.md matches the artifacts."); return 0
        print("DRIFT: AUDIT_MATRIX.md disagrees with the artifacts.", file=sys.stderr); return 1
    print(text, end=""); return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
