#!/usr/bin/env python3
"""emit_gate_status: the ONE place any GATE COUNT in prose comes from.

Sibling of emit_public_numbers.py, same contract, different artifact class. That script covers
register counts; nothing covered CHECK counts -- and in the 2026-08-22 session three separate
status summaries stated a gate result that disagreed with the artifact ("factor 2/pi^2 correct"
after it was corrected; "4/5" after R3 went green; both while the code was right). Zero physics
errors, three prose drifts. A summary that READS the artifact cannot drift; one that RETYPES it
will.

Run:  python3 emit_gate_status.py <YYYY-MM-DD>            print the dated block
      python3 emit_gate_status.py <YYYY-MM-DD> --write    write it to ../GATE_STATUS.md
      python3 emit_gate_status.py <YYYY-MM-DD> --check    regenerate and diff against the file

The date is an ARGUMENT, never `today` -- a block that silently re-dates itself on every run
cannot be diffed (emit_public_numbers.py's rule, inherited deliberately).

Reads only *_STATUS.json artifacts emitted by the calcs themselves. It runs nothing and
interprets nothing: counts and pass/fail, no prose.
"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "GATE_STATUS.md")


def block(date):
    lines = ["# GATE_STATUS -- emitted, never hand-typed", "",
             "*Generated by `provenance/emit_gate_status.py %s`. Counts and pass/fail only;"
             " no interpretation. Do not edit: regenerate.*" % date, ""]
    paths = sorted(glob.glob(os.path.join(ROOT, "*_STATUS.json")))
    if not paths:
        lines.append("*(no `*_STATUS.json` artifacts present)*")
        return "\n".join(lines) + "\n"
    lines += ["| artifact | verdict | passing |", "|---|---|---|"]
    for p in paths:
        name = os.path.basename(p)
        try:
            d = json.load(open(p))
        except Exception as e:
            lines.append("| `%s` | UNREADABLE (%s) | - |" % (name, type(e).__name__))
            continue
        checks = d.get("checks") or []
        npass = sum(1 for c in checks if c.get("pass"))
        verdict = str(d.get("verdict", "(none)"))
        lines.append("| `%s` | %s | **%d/%d** |" % (name, verdict, npass, len(checks)))
    lines.append("")
    for p in paths:
        try:
            d = json.load(open(p))
        except Exception:
            continue
        checks = d.get("checks") or []
        if not checks:
            continue
        lines.append("### `%s`" % os.path.basename(p))
        lines.append("")
        for c in checks:
            lines.append("- %s **%s** -- %s%s" % (
                "ok" if c.get("pass") else "FAIL", c.get("id", "?"),
                c.get("desc", ""), (" -- " + c["detail"]) if c.get("detail") else ""))
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) < 2 or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", argv[1]):
        print("usage: emit_gate_status.py <YYYY-MM-DD> [--write|--check]", file=sys.stderr)
        return 2
    date, mode = argv[1], (argv[2] if len(argv) > 2 else "")
    text = block(date)
    if mode == "--write":
        open(OUT, "w").write(text); print("wrote %s" % OUT); return 0
    if mode == "--check":
        if not os.path.exists(OUT):
            print("MISSING: %s" % OUT, file=sys.stderr); return 1
        cur = open(OUT).read()
        # compare ignoring the generation date line
        strip = lambda t: "\n".join(l for l in t.splitlines() if "emit_gate_status.py" not in l)
        if strip(cur) == strip(text):
            print("GATE_STATUS.md matches the artifacts."); return 0
        print("DRIFT: GATE_STATUS.md disagrees with the *_STATUS.json artifacts.",
              file=sys.stderr); return 1
    print(text, end=""); return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
