"""test_public_numbers: THE ONE-NUMBER RULE, made real.

The rule (overseer, 2026-08-12): no count is ever typed into the public document's prose. Every
count is emitted by provenance/emit_public_numbers.py from claims.json on a stated date and
included verbatim. A rule of this kind is only real if a script enforces it -- otherwise it is a
resolution, and this program's own history is a list of resolutions that decayed.

Note the derived-tier assertion below: `derived` is EMPTY, and the public document's headline
depends on it. If a claim is ever graduated to `derived`, this test fails and the headline must be
rewritten before it can pass -- which is the intended coupling.
"""
import os
import subprocess
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BLOCK = os.path.join(ROOT, "PUBLIC_NUMBERS.md")


class TestPublicNumbers(unittest.TestCase):

    def test_the_block_exists(self):
        self.assertTrue(os.path.exists(BLOCK),
                        "PUBLIC_NUMBERS.md missing -- generate with "
                        "`python3 provenance/emit_public_numbers.py --write`")

    def test_no_drift_from_the_register(self):
        r = subprocess.run([sys.executable, os.path.join(HERE, "emit_public_numbers.py"), "--check"],
                           capture_output=True, text=True, timeout=600)
        self.assertEqual(r.returncode, 0,
                         f"the emitted numbers no longer match the register:\n{r.stdout}")

    def test_the_block_is_marked_generated(self):
        head = open(BLOCK).read()[:300]
        self.assertIn("GENERATED by provenance/emit_public_numbers.py", head)
        self.assertIn("DO NOT EDIT BY HAND", head)

    def test_the_derived_tier_is_still_empty(self):
        """The public document's central negative claim -- zero novel positive predictions -- is a
        statement about this cell. Coupled deliberately: graduate a claim to `derived` and this
        fails until the headline is rewritten."""
        import json
        cl = json.load(open(os.path.join(HERE, "claims.json")))["claims"]
        derived = [c["id"] for c in cl
                   if c.get("ledger_scope", "grut") == "grut" and c["tier"] == "derived"]
        self.assertEqual(derived, [],
                         f"the `derived` tier is no longer empty ({derived}) -- the public "
                         f"document's 'zero novel positive predictions' headline must be rewritten "
                         f"before this can pass")

    def test_the_stamped_test_count_is_true(self):
        """The block's test count is a stamped constant (the emitter must not recurse through
        pytest). It is enforced HERE against a real collection, so the constant cannot rot."""
        import emit_public_numbers as E
        r = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q"],
                           cwd=HERE, capture_output=True, text=True, timeout=600)
        lines = [l for l in r.stdout.strip().split("\n") if "collected" in l or "tests" in l]
        nums = [int(w) for l in lines for w in l.split() if w.isdigit()]
        self.assertTrue(nums, f"could not parse a collection count from:\n{r.stdout[-400:]}")
        self.assertEqual(E.STAMPED_TEST_COUNT, max(nums),
                         f"STAMPED_TEST_COUNT is {E.STAMPED_TEST_COUNT} but the suite collects "
                         f"{max(nums)} -- update the constant and regenerate PUBLIC_NUMBERS.md")

    def test_the_emitter_does_not_recurse_through_pytest(self):
        """Check for INVOCATION, not for the word. The first draft asserted "pytest" was absent
        from the file and then failed on the comment explaining why pytest is not invoked -- a
        guard tripping over its own rationale, the same shape as the glossary case earlier the
        same day. No subprocess import means no recursion is reachable."""
        import emit_public_numbers as E
        self.assertFalse(hasattr(E, "subprocess"),
                         "the number-emitter must not import subprocess -- the drift check would "
                         "then run pytest from inside pytest, and adding a test would change the "
                         "number the block asserts")
        src = open(os.path.join(HERE, "emit_public_numbers.py")).read()
        for call in ('"-m", "pytest"', "subprocess.run", "os.system", "os.popen"):
            self.assertNotIn(call, src, f"emitter must not shell out ({call} found)")

    def test_the_stamp_date_is_fixed_not_today(self):
        """A block that silently re-dates itself on every run cannot be diffed."""
        import emit_public_numbers as E
        import datetime
        self.assertRegex(E.STAMP_DATE, r"^\d{4}-\d{2}-\d{2}$")
        src = open(os.path.join(HERE, "emit_public_numbers.py")).read()
        self.assertNotIn("datetime.date.today", src,
                         "the stamp must be a fixed argument, never `today`")

    def test_figures_match_their_generators(self):
        """Generated figures obey the same rule as generated counts: a hand-edited figure is a
        build failure, not a reading error. Figure 1 re-derives from the register, so a tier
        change that did not reach the figure fails here."""
        r = subprocess.run([sys.executable, os.path.join(HERE, "build_figures.py"), "--check"],
                           capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, f"figures drifted:\n{r.stdout}{r.stderr}")
